### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by judemont** [DustinBrett/daedalOS#290]
Hello,
When I run `python` in the terminal I get this error:
```
Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/_pyodide/_base.py", line 531, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 357, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 4, in <module>
NameError: name 'python' is not defined
```

**Comment by DustinBrett** [comment]
Ok thanks I'll check this out. I see `python version` and `python 1+1` work, so I may have just forgot to handle no args being passed.

**Comment by DustinBrett** [comment]
Fixed this. Indeed it was passing `python` as the command itself which was wrong.

https://github.com/DustinBrett/daedalOS/commit/05ae7bc5d2b1a98a1213fa248a02c075819664ac
